### Fancy Indexing

In [2]:
import numpy as np

In [3]:
# Fancy indexing in single dimension

rand = np.random.RandomState(42)

x = rand.randint(100, size=10)

In [4]:
x

array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74])

In [5]:
x[2], x[3], x[7]

(14, 71, 86)

In [6]:
ind = [2, 7, 3]
x[ind]

array([14, 86, 71])

In [7]:
# Create a new array using x
ind = np.array([[3, 7], 
                [4, 5]])

In [8]:
x[ind]

array([[71, 86],
       [60, 20]])

### Fancy Indexing in multiple dimensions

In [46]:
x = np.arange(12).reshape(3, 4)

In [47]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
# Create a new array by X with bnelow index
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])

In [49]:
x[row, col]

array([ 2,  5, 11])

In [50]:
# Create a new array that is a submatrix of x
x[row[:, np.newaxis], col]

array([[ 2,  1,  3],
       [ 6,  5,  7],
       [10,  9, 11]])

### Combined Indexing

In [51]:
# Combine fancy indice and simple indices
x[2, [2, 0, 2]]

array([10,  8, 10])

In [52]:
# Combine fancy indices with slicing
x[1:, [2, 0, 1]]

array([[ 6,  4,  5],
       [10,  8,  9]])

In [54]:
# Combine fancy indices with mask
mask = np.array([1, 0, 1, 0], dtype=bool)

In [55]:
mask

array([ True, False,  True, False])

In [56]:
x[row[:, np.newaxis], mask]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

### Modify value with Fancy Indexing

In [57]:
x = np.arange(10)

i = np.array([2, 1, 8, 4])

In [58]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
i

array([2, 1, 8, 4])

In [60]:
x[i]

array([2, 1, 8, 4])

In [61]:
x[i] = 99

In [62]:
x

array([ 0, 99, 99,  3, 99,  5,  6,  7, 99,  9])

In [63]:
# Adding value
x[i] += 10

In [64]:
x

array([  0, 109, 109,   3, 109,   5,   6,   7, 109,   9])

In [65]:
# Subtracting value
x[i] -= 10

In [66]:
x

array([ 0, 99, 99,  3, 99,  5,  6,  7, 99,  9])

In [67]:
# if give multiple value behind will overwrite it
x[[0, 0]] = [4, 6] 

In [68]:
x

array([ 6, 99, 99,  3, 99,  5,  6,  7, 99,  9])

In [78]:
x = np.zeros(10)

In [79]:
i = [1, 2, 2, 3, 3, 3, 4, 4, 4, 4]

In [80]:
x[i] += 1

In [81]:
x

array([0., 1., 1., 1., 1., 0., 0., 0., 0., 0.])

In [82]:
np.add.at(x, i, 1)

In [83]:
x

array([0., 2., 3., 4., 5., 0., 0., 0., 0., 0.])

### Sorting Arrays

In [84]:
x = np.array([5, 4, 32, 1])

In [85]:
np.sort(x)

array([ 1,  4,  5, 32])

In [88]:
x.sort()

In [89]:
x

array([ 1,  4,  5, 32])

In [90]:
# To get the indices of sorted elements
i = np.argsort(x)

In [92]:
print(f'Sort indices: {i}')
print(f'Sort elements: {x}')

Sort indices: [0 1 2 3]
Sort elements: [ 1  4  5 32]


In [93]:
# Starting of arrays with rows and columns
rand = np.random.RandomState(42)
x = rand.randint(0, 10, (4, 6))

In [94]:
x

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [95]:
# Sort each element of column
np.sort(x, axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [96]:
# Sort each element of row
np.sort(x, axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

### Partial Sorting: Partitioning

In [97]:
x = np.array([99, 88, 77, 66, 55, 44, 33, 22, 11])

In [98]:
x

array([99, 88, 77, 66, 55, 44, 33, 22, 11])

In [101]:
# Give smallest values to the left of the partition, and remaining values to the right in arbitary order
np.partition(x, 3)

array([22, 11, 33, 44, 55, 88, 66, 77, 99])

In [125]:
rand = np.random.RandomState(42)
x = rand.randint(0, 10, (4, 6))

In [126]:
x

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [128]:
np.partition(x, 2, axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [129]:
np.partition(x, 2, axis=1)

array([[3, 4, 6, 7, 6, 9],
       [2, 3, 4, 7, 6, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 9, 5]])

### Structure Data

In [157]:
# Create a compound dtype by specifying them as a list (square brackets) of tuple (parenthesis)
datatype = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]

In [158]:
datatype

[('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]

In [159]:
# Create values by specifing them as a list (square brackets) of tuple (parenthesis)
values = [('Rex', 9, 81.0), ('Fido', 3, 27.0), ('Bob', 45, 85.5)]

In [160]:
f = np.array(values, dtype=datatype)

In [161]:
f

array([('Rex',  9, 81. ), ('Fido',  3, 27. ), ('Bob', 45, 85.5)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])