# MIS132 程式設計實習 - Lecture10

## Outline this week

- NumPy 矩陣運算
  - 數值運算、矩陣乘法
  - 常用的函式
  - Indexing、Slicing
- Lab 練習

## NumPy 矩陣運算
### 數值運算

NumPy 的 array 可以直接套用 +、-、*、/......等基本運算

但是陣列的 size 要相同才可以

In [1]:
import numpy as np

In [2]:
a = np.arange(4, 9)
print('a', a)
b = np.ones(5) * 2
print('b', b)

a [4 5 6 7 8]
b [2. 2. 2. 2. 2.]


In [3]:
print('a + b', a + b)
print('a - b', a - b)

a + b [ 6.  7.  8.  9. 10.]
a - b [2. 3. 4. 5. 6.]


In [4]:
# 注意這兩個是 dot-wise
print('a * b', a * b)
print('a / b', a / b)

a * b [ 8. 10. 12. 14. 16.]
a / b [2.  2.5 3.  3.5 4. ]


來點複雜的運算

In [5]:
# truncate
print('a // b', a // b)

a // b [2. 2. 3. 3. 4.]


In [6]:
print('a ** b', a ** b)

a ** b [16. 25. 36. 49. 64.]


In [7]:
a += 2
print('a += 2', a)

a += 2 [ 6  7  8  9 10]


In [8]:
b -= 3
print('b -= 3', b)

b -= 3 [-1. -1. -1. -1. -1.]


### 矩陣乘法

![](https://i.imgur.com/VlBLSXb.png)

In [9]:
a = np.array([[1, 2], [3, 4]])
print('a', a)
b = np.array([[5, 6], [7, 8]])
print('b', b)
print('-' * 20)

print('Matrix Multiplication')
print(a.dot(b))
# or
print(np.dot(a, b))

print('Dot-wise Multiplication')
print(a * b)

a [[1 2]
 [3 4]]
b [[5 6]
 [7 8]]
--------------------
Matrix Multiplication
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
Dot-wise Multiplication
[[ 5 12]
 [21 32]]


### 常用函式

NumPy 裡面有「非常多」數值運算的 Function、常數......等

先來點簡單的

In [10]:
print('pi\t', np.pi)
print('e\t', np.e)
print('log(e)\t', np.log(10))
print('log(2)\t', np.log2(100))
print('log(10)\t', np.log10(1000))

pi	 3.141592653589793
e	 2.718281828459045
log(e)	 2.302585092994046
log(2)	 6.643856189774724
log(10)	 3.0


當然也支援一整個陣列的運算

In [20]:
a = np.random.randint(0, 5, size=4)
a

array([4, 3, 1, 2])

In [21]:
print('log(e)\t', np.log(a))
print('log(2)\t', np.log2(a))
print('log(10)\t', np.log10(a))
print('sqrt\t', np.sqrt(a))
print('exp\t', np.exp(a))

log(e)	 [1.38629436 1.09861229 0.         0.69314718]
log(2)	 [2.        1.5849625 0.        1.       ]
log(10)	 [0.60205999 0.47712125 0.         0.30103   ]
sqrt	 [2.         1.73205081 1.         1.41421356]
exp	 [54.59815003 20.08553692  2.71828183  7.3890561 ]


#### Indexing & slicing

NumPy 支援原生 Python 大部分的 indexing

In [22]:
a = np.arange(3, 10)
a

array([3, 4, 5, 6, 7, 8, 9])

In [23]:
a[2:5]

array([5, 6, 7])

In [24]:
a[1:6:2]

array([4, 6, 8])

In [25]:
a[4::-1]

array([7, 6, 5, 4, 3])

In [26]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3])

值得注意的是，當我們 array 維度 >= 2 的時候，我們的 NumPy indexing 會比較複雜

我們可以使用 ` , ` 來分隔多個維度的 indexing

```python
arr[d1_start:d1_end , d2_start:d2_end]
```

In [27]:
a = np.arange(16).reshape(4, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [28]:
a[1:3]
# 這樣只會取出 row 的資料

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
a[0:2, 0:3]

array([[0, 1, 2],
       [4, 5, 6]])

In [30]:
a[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])

如果我只想取出 column 的資料呢？

我們可以在要「全部取出」的 dimension 使用 ` : ` 來代表省略

In [31]:
a[:, 1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [32]:
a[:, 2:4]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

### Lab練習

請開啟一份新的 .ipynb 筆記檔案, 檔名為「L10.ipynb」，寫完上傳至網大.

### 請利用 numpy 建立以下 array

1. 建立一個 6x6 的矩陣，讓 1,2,3,4,5 落在對角線上，並取出部分 matrix hint:  
**Hint: indexing + assign   or  np.diag**  

    1. 先建立
    ```python
    [[1 0 0 0 0]
     [0 2 0 0 0]
     [0 0 3 0 0]
     [0 0 0 4 0]
     [0 0 0 0 5]]
    ```
    2. 再取出
    ```python
    [[0 3 0 0]
     [0 0 4 0]
     [0 0 0 5]]
    ```
2. 建立從 0 ~ pi * 2 的隨機 array，裡面包含 21 個元素，並對該陣列取 cos 或 sin
    1. 建立矩陣隨機 array，下方為範例
    ```python
    [ 0.          0.31415927  0.62831853  0.9424778   1.25663706  1.57079633
      1.88495559  2.19911486  2.51327412  2.82743339  3.14159265  3.45575192
      3.76991118  4.08407045  4.39822972  4.71238898  5.02654825  5.34070751
      5.65486678  5.96902604  6.28318531]
    ```
    2. 對 array 取 cos(or sin)，下方為範例
    ```python
    [  1.00000000e+00   9.51056516e-01   8.09016994e-01   5.87785252e-01
       3.09016994e-01   6.12323400e-17  -3.09016994e-01  -5.87785252e-01
      -8.09016994e-01  -9.51056516e-01  -1.00000000e+00  -9.51056516e-01
      -8.09016994e-01  -5.87785252e-01  -3.09016994e-01  -1.83697020e-16
       3.09016994e-01   5.87785252e-01   8.09016994e-01   9.51056516e-01
       1.00000000e+00]
    ```
3. 請找一個 numpy 有關 數值運算、線性代數的函式，並附上至少兩個範例 code