In [2]:
# import relate packages
import numpy as np

In [83]:
np.random.seed(0)
X1 = np.random.randint(100, size = (10))
X2 = np.random.randint(100, size = (4, 4))

**Question 1: Fancy Indexing**

- a. Print X1
- b. Print the 2nd, 6th, 3rd, 8th (0-indexing) elements in X1
- c. Create a new array by X1 with index [ 2, 6, 3, 8 ]
- d. Create a new array by X1 with index [ [2, 6], [3, 8] ]

In [4]:
# a.
print(X1)

[44 47 64 67 67  9 83 21 36 87]


In [5]:
# b.
print(f'{X1[2]}\n{X1[6]}\n{X1[3]}\n{X1[8]}')

64
83
67
36


In [6]:
# c.
select1 = np.array([2, 6, 3, 8])
print(X1[select1])

[64 83 67 36]


In [8]:
# d. 
print(X1[select1.reshape([2, 2])])

[[64 83]
 [67 36]]


**Question 2: Fancy Indexing**

- a. print X2
- b. print the [1,3], [2,2], [3,1] elements in X2
- c. create a new array by X2 with index [[1, 2, 3], [3, 2, 1]]
- d. create a new array that is a submatrix of X2
    - whose rows are indexed by [1, 2, 3] and
    - whose columns are indexed by [3, 2, 1]
    - Try use: [row[:, np.newaxis], col]

In [9]:
# a.
print(X2)

[[70 88 88 12]
 [58 65 39 87]
 [46 88 81 37]
 [25 77 72  9]]


In [15]:
# b.
print(f'{X2[1, 3]}\n{X2[2, 2]}\n{X2[3, 1]}')


87
81
77


In [18]:
# c.
select2 = np.array([[1, 2, 3], [3, 2, 1]])
print(X2[select2[0], select2[1]])

[87 81 77]


In [17]:
# d.
print(X2[select2[0][:, np.newaxis], select2[1]])

[[87 39 65]
 [37 81 88]
 [ 9 72 77]]


**Q3: Combining fancy indexing with other indexing schemes**

- a. print X2
- b. print the 3rd (0-indexing) row of X2 as a 1-dimensional array
- c. print a 1-dimensional array
     - whose entries are the 3rd, 1st, 2nd entries of the 3rd row of X2
- d. create a new array that is a submatrix of X2
     - whose rows are indexed by [2,1] and
     - whose columns are indexed by [3,1,2]

In [21]:
# a.
print(X2)

[[70 88 88 12]
 [58 65 39 87]
 [46 88 81 37]
 [25 77 72  9]]


In [28]:
# b.
print(X2[3])

[25 77 72  9]


In [43]:
# c.
print(X2[3:, [3, 1, 2]])

[[ 9 77 72]]


In [44]:
# d.
print(X2[[2, 1], :][:, [3, 1, 2]])

[[37 88 81]
 [87 65 39]]


**Q4: Modifying values with fancy indexing**

In [54]:
X3 = np.arange(10)

- a. print X3
- b. change the 3rd, 6th, 8th values in X3 into 15
- c. substract 10 from the 2nd, 6th and 8th elements in X3

In [55]:
# a.
print(X3)

[0 1 2 3 4 5 6 7 8 9]


In [56]:
# b.
X3[[3, 6, 8]] = 15
print(X3)

[ 0  1  2 15  4  5 15  7 15  9]


In [57]:
X3[[2, 6, 8]] -= 10
print(X3)

[ 0  1 -8 15  4  5  5  7  5  9]


**Q5: Sorting and argsorting of rows or columns**

- a. sort each column of X2
- b. sort each row of X2
- c. gives the order index along the columns of X2
- d. gives the order index along the rows of X2

In [66]:
X2

array([[70, 88, 88, 12],
       [58, 65, 39, 87],
       [46, 88, 81, 37],
       [25, 77, 72,  9]])

In [80]:
# a.
np.sort(X2, axis=0)

array([[25, 65, 39,  9],
       [46, 77, 72, 12],
       [58, 88, 81, 37],
       [70, 88, 88, 87]])

In [84]:
# b.
np.sort(X2, axis=1)

array([[12, 70, 88, 88],
       [39, 58, 65, 87],
       [37, 46, 81, 88],
       [ 9, 25, 72, 77]])

In [85]:
# c.
np.argsort(X2, axis=0)

array([[3, 1, 1, 3],
       [2, 3, 3, 0],
       [1, 0, 2, 2],
       [0, 2, 0, 1]], dtype=int64)

In [86]:
# d.
np.argsort(X2, axis=1)

array([[3, 0, 1, 2],
       [2, 0, 1, 3],
       [3, 0, 2, 1],
       [3, 0, 2, 1]], dtype=int64)