In [157]:
# Import related packages

import numpy as np
import pandas as pd

In [158]:
# Related data

A1 = pd.DataFrame([[12, np.nan, 23, 25 ],
                   [18, None, 52, 34 ],
                   [np.nan, 14, 39, None],
                   [37, 76, 19, 10 ],
                   [47, 66, 29, 1 ]])

C1_index = [('California', 2000), ('California', 2010),
            ('New York', 2000), ('New York', 2010),
            ('Texas', 2000), ('Texas', 2010)]

populations = [33871648, 37253956, 18976457, 19378102, 20851820, 25145561]

C1 = pd.Series(populations, index=C1_index)

Data = np.round(np.random.randn(4, 6), 1)
Data[:, ::2] *= 10
Data += 37

H1=pd.DataFrame([['A1','B1','C1'],['A2','B2','C2']], index=['1','2'], columns=['A','B','C'])
H2=pd.DataFrame([['B3','C3','D3'],['B4','C4','D4']], index=['1','2'], columns=['B','C','D'])

# Q1: Detecting and droping null values

- a. print A1
- b. detecting null values in A1
- c. drop the rows which contain null in A1
- d. drop the columns which contain null in A1
- e. Keep minimum 4 non-NA entries column-wise

In [159]:
A1 = pd.DataFrame([[12, np.nan, 23, 25 ],
                   [18, None, 52, 34 ],
                   [np.nan, 14, 39, None],
                   [37, 76, 19, 10 ],
                   [47, 66, 29, 1 ]],
                 columns=list('ABCD'))

In [160]:
# a. 
print(A1)

      A     B   C     D
0  12.0   NaN  23  25.0
1  18.0   NaN  52  34.0
2   NaN  14.0  39   NaN
3  37.0  76.0  19  10.0
4  47.0  66.0  29   1.0


In [161]:
# b.detecting null values in A1

A1.isnull()

A      B      C      D
0  False   True  False  False
1  False   True  False  False
2   True  False  False   True
3  False  False  False  False
4  False  False  False  False

In [162]:
# c. drop the rows which contain null in A1

A1.dropna()

A     B   C     D
3  37.0  76.0  19  10.0
4  47.0  66.0  29   1.0

In [163]:
# d. drop the columns which contain null in A1

A1.dropna(axis=1)

C
0  23
1  52
2  39
3  19
4  29

In [164]:
# e. Keep minimum 4 non-NA entries column-wise

A1.dropna(axis=1, thresh=4)

A   C     D
0  12.0  23  25.0
1  18.0  52  34.0
2   NaN  39   NaN
3  37.0  19  10.0
4  47.0  29   1.0

# Q2: Filling null values

- a. print A1
- b. Replace all NaN elements in column 'A', 'B', 'C', and 'D', with 0, 1, 2, and 3 respectively. hint (use value parameter)
- c. Only replace the first NaN element. by default it is column-wise. (hint: use value and limit parameters)
- d. forward-fill the previous value by axis 1

In [165]:
# a. print A1

print(A1)

      A     B   C     D
0  12.0   NaN  23  25.0
1  18.0   NaN  52  34.0
2   NaN  14.0  39   NaN
3  37.0  76.0  19  10.0
4  47.0  66.0  29   1.0


In [166]:
# b. Replace all NaN elements in column 'A', 'B', 'C', and 'D', with 0, 1, 2, and 3 respectively.
# hint (use value parameter)

A1.fillna(value={'A': 0, 'B': 1, 'C': 2, 'D': 3})

A     B   C     D
0  12.0   1.0  23  25.0
1  18.0   1.0  52  34.0
2   0.0  14.0  39   3.0
3  37.0  76.0  19  10.0
4  47.0  66.0  29   1.0

In [167]:
# c. Only replace the first NaN element. by default it is column-wise. (hint: use value and limit parameters)

A1.fillna(value={'A': 0, 'B': 1, 'C': 2, 'D': 3}, limit=1)

A     B   C     D
0  12.0   1.0  23  25.0
1  18.0   NaN  52  34.0
2   0.0  14.0  39   3.0
3  37.0  76.0  19  10.0
4  47.0  66.0  29   1.0

In [168]:
# d. forward-fill the previous value by axis 1

A1.fillna(method='ffill', axis=1)

A     B     C     D
0  12.0  12.0  23.0  25.0
1  18.0  18.0  52.0  34.0
2   NaN  14.0  39.0  39.0
3  37.0  76.0  19.0  10.0
4  47.0  66.0  29.0   1.0

# Q3: MultiIndex as extra dimension

- a. print C1
- b. print C1_index
- c. convert C1_index as Pandas MultiIndex type
- d. re-index the C1 with C1_index, then name as C1d
- e. use unstack way to convert C1d, then name as C1e
- f. use stack way to convert C1e, then name as C1f

In [169]:
# Run before the start of answering question 3

C1_index = [('California', 2000), ('California', 2010),
            ('New York', 2000), ('New York', 2010),
            ('Texas', 2000), ('Texas', 2010)]


populations = [33871648, 37253956, 18976457, 19378102, 20851820, 25145561]

In [170]:
# a. print C1
# That is a Series multi-indexing

C1 = pd.Series(populations, index=C1_index)
print(C1)

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64


In [171]:
# b. print C1_index
print(C1_index)

[('California', 2000), ('California', 2010), ('New York', 2000), ('New York', 2010), ('Texas', 2000), ('Texas', 2010)]


In [195]:
# c. convert C1_index as Pandas MultiIndex type

C1_index = pd.MultiIndex.from_tuples(C1_index)
print(C1)

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64


In [173]:
# d. re-index the C1 with C1_index, then name as C1d

C1d = C1.reindex(C1_index)
print(C1d)

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64


In [174]:
# e. use unstack way to convert C1d, then name as C1e

C1e = C1d.unstack()
print(C1e)

                2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561


In [175]:
# f. use stack way to convert C1e, then name as C1f

C1f = C1e.stack()
print(C1f)

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64


# Q4: MultiIndex for columns

- a. create "row_index" by MultiIndex.from_product which contain
        levels=[[2013, 2014], [1, 2]],
        names=['year', 'visit']

- b. create "column_index" by MultiIndex.from_product which contain
        levels=[['Bob', 'Guido', 'Sue'], ['HR', 'Temp']],
        names=['patient', 'measurement']

- c. combine "row_index", "column_index" and Data by pd.DataFrame as D2

In [176]:
# a. 

row_index = pd.MultiIndex.from_product([[2013, 2014], [1, 2]], names=['year', 'visit'])
print(row_index)

MultiIndex([(2013, 1),
            (2013, 2),
            (2014, 1),
            (2014, 2)],
           names=['year', 'visit'])


In [177]:
# b.

column_index = pd.MultiIndex.from_product([['Bob', 'Guido', 'Sue'], ['HR', 'Temp']], names=['patient', 'measurement'])
print(column_index)

MultiIndex([(  'Bob',   'HR'),
            (  'Bob', 'Temp'),
            ('Guido',   'HR'),
            ('Guido', 'Temp'),
            (  'Sue',   'HR'),
            (  'Sue', 'Temp')],
           names=['patient', 'measurement'])


In [178]:
# Run before answering Question 4c.

Data = np.round(np.random.randn(4, 6), 1)
Data[:, ::2] *= 10
Data += 37
print(Data)

[[53.  37.3 35.  38.4 50.  36.2]
 [34.  37.1 28.  37.8 22.  37.6]
 [41.  36.6 39.  37.5 67.  37.1]
 [48.  36.7 26.  37.3 21.  36.6]]


In [179]:
# c. combine "row_index", "column_index" and Data by pd.DataFrame as D2

D2 = pd.DataFrame(Data, index=row_index, columns=column_index)
print(D2)

patient       Bob       Guido         Sue      
measurement    HR  Temp    HR  Temp    HR  Temp
year visit                                     
2013 1       53.0  37.3  35.0  38.4  50.0  36.2
     2       34.0  37.1  28.0  37.8  22.0  37.6
2014 1       41.0  36.6  39.0  37.5  67.0  37.1
     2       48.0  36.7  26.0  37.3  21.0  36.6


# Q5: Multiple index DataFrames

- a. print D2
- b. select 'Sue' column from D2
- c. select 'HR' column in 'Sue' column from D2
- d. select '2014' row and 'Guido' column from D2. (using iloc)
- e. select '2013' row and 'HR' column in 'Guido' column from D2. (using loc)
- f. select 'visit'=2 row and 'Temp' column from D2. (recall loc and idx)

In [180]:
# a.

print(D2)

patient       Bob       Guido         Sue      
measurement    HR  Temp    HR  Temp    HR  Temp
year visit                                     
2013 1       53.0  37.3  35.0  38.4  50.0  36.2
     2       34.0  37.1  28.0  37.8  22.0  37.6
2014 1       41.0  36.6  39.0  37.5  67.0  37.1
     2       48.0  36.7  26.0  37.3  21.0  36.6


In [181]:
# b. select 'Sue' column from D2

D2.loc[:, 'Sue']

measurement    HR  Temp
year visit             
2013 1       50.0  36.2
     2       22.0  37.6
2014 1       67.0  37.1
     2       21.0  36.6

In [182]:
# c. select 'HR' column in 'Sue' column from D2
D2['Sue', 'HR']

year  visit
2013  1        50.0
      2        22.0
2014  1        67.0
      2        21.0
Name: (Sue, HR), dtype: float64

In [196]:
# d. select '2014' row and 'Guido' column from D2. (using iloc)
D2.iloc[2:4,2:4]

patient     Guido      
measurement    HR  Temp
year visit             
2014 1       39.0  37.5
     2       26.0  37.3

In [184]:
# e. select '2013' row and 'HR' column in 'Guido' column from D2. (using loc)
D2.loc[2013, ('Guido', 'HR')]

visit
1    35.0
2    28.0
Name: (Guido, HR), dtype: float64

In [185]:
# f. select 'visit'=2 row and 'Temp' column from D2. (recall loc and idx)
idx = pd.IndexSlice
D2.loc[idx[:, 2], idx[:, 'Temp']]

patient       Bob Guido   Sue
measurement  Temp  Temp  Temp
year visit                   
2013 2       37.1  37.8  37.6
2014 2       36.7  37.3  36.6

# Q6: Data Aggregations on Multi-Indices

- a. print D2
- b. take the sum among levels on the visit row
- c. take the sum among levels on the patient column

In [186]:
# a.

print(D2)

patient       Bob       Guido         Sue      
measurement    HR  Temp    HR  Temp    HR  Temp
year visit                                     
2013 1       53.0  37.3  35.0  38.4  50.0  36.2
     2       34.0  37.1  28.0  37.8  22.0  37.6
2014 1       41.0  36.6  39.0  37.5  67.0  37.1
     2       48.0  36.7  26.0  37.3  21.0  36.6


In [187]:
# b. take the sum among levels on the visit row
D2.groupby('visit').sum()

patient       Bob       Guido          Sue      
measurement    HR  Temp    HR  Temp     HR  Temp
visit                                           
1            94.0  73.9  74.0  75.9  117.0  73.3
2            82.0  73.8  54.0  75.1   43.0  74.2

In [188]:
# c. take the sum among levels on the patient column

D2.groupby('patient', axis=1).sum()

patient      Bob  Guido    Sue
year visit                    
2013 1      90.3   73.4   86.2
     2      71.1   65.8   59.6
2014 1      77.6   76.5  104.1
     2      84.7   63.3   57.6

# Q7: Simple Concatenation with pd.concat

- a. print E1
- b. print E2
- c. concat E1 and E2 by row
- d. fix the duplicate indices problem on c (hint: use ignore_index)
- e. concat E1 and E2 by column

In [189]:
E1=pd.DataFrame([['A1','B1','C1'],['A2','B2','C2']], index=['1','2'], columns=['A','B','C'])

E2=pd.DataFrame([['B3','C3','D3'],['B4','C4','D4']], index=['1','2'], columns=['B','C','D'])

In [190]:
# a. 

print(E1)

    A   B   C
1  A1  B1  C1
2  A2  B2  C2


In [191]:
# b.

print(E2)

    B   C   D
1  B3  C3  D3
2  B4  C4  D4


In [192]:
# c.

pd.concat([E1, E2])

A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
1  NaN  B3  C3   D3
2  NaN  B4  C4   D4

In [193]:
# d.

pd.concat([E1, E2], ignore_index=True)

A   B   C    D
0   A1  B1  C1  NaN
1   A2  B2  C2  NaN
2  NaN  B3  C3   D3
3  NaN  B4  C4   D4

In [194]:
# concat H1 and H2 by column

pd.concat([E1, E2], axis=1)

A   B   C   B   C   D
1  A1  B1  C1  B3  C3  D3
2  A2  B2  C2  B4  C4  D4