# import relate packages

In [22]:
# import relate packages
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.metrics import mean_squared_error
from sklearn.metrics import classification_report, confusion_matrix
import warnings
warnings.filterwarnings('ignore')

## Run before answer

In [23]:
A1 = [
{'price': 850000, 'rooms': 4, 'neighborhood': 'Queen Anne'},
{'price': 700000, 'rooms': 3, 'neighborhood': 'Fremont'},
{'price': 650000, 'rooms': 3, 'neighborhood': 'Wallingford'},
{'price': 600000, 'rooms': 2, 'neighborhood': 'Fremont'}]

B1 = ["Human machine interface for lab computer",
"A survey of user opinion of computer system",
"User interface management system",
"Graph minors A survey"]

from numpy import nan

C1 = np.array([[ nan, 0, 3 ],
                [ 3, 7, 9 ],
                [ 3, 5, 2 ],
                [ 4, nan, 6 ],
                [ 8, 8, 1 ]])

# Q1: Feature Engineering - Categorical Features

- a. print A1
- b. import DictVectorizer from sklearn
- c. Vectorize the A1 with sparse=False, and print
- d. Vectorize the A1 with sparse=True, and print
- e. print the feature name of c. or d.

## Q1a print A1

In [24]:
## here for print code
print(A1)

[{'price': 850000, 'rooms': 4, 'neighborhood': 'Queen Anne'}, {'price': 700000, 'rooms': 3, 'neighborhood': 'Fremont'}, {'price': 650000, 'rooms': 3, 'neighborhood': 'Wallingford'}, {'price': 600000, 'rooms': 2, 'neighborhood': 'Fremont'}]


## Q1b import DictVectorizer from sklearn

In [25]:
## here for import code
from sklearn.feature_extraction import DictVectorizer

## Q1c Vectorize the A1 with sparse=False, and print

In [44]:
## here for print code
vec1 = DictVectorizer(sparse=False, dtype=int)
print(vec1.fit_transform(A1))

[[     0      1      0 850000      4]
 [     1      0      0 700000      3]
 [     0      0      1 650000      3]
 [     1      0      0 600000      2]]


## Q1d Vectorize the A1 with sparse=True, and print

In [43]:
## here for print code
vec2 = DictVectorizer(sparse=True, dtype=int)
print(vec2.fit_transform(A1))

  (0, 1)	1
  (0, 3)	850000
  (0, 4)	4
  (1, 0)	1
  (1, 3)	700000
  (1, 4)	3
  (2, 2)	1
  (2, 3)	650000
  (2, 4)	3
  (3, 0)	1
  (3, 3)	600000
  (3, 4)	2


## Q1e print the feature name of c. or d.

In [45]:
## here for print code
print(vec1.get_feature_names())
print(vec2.get_feature_names())

['neighborhood=Fremont', 'neighborhood=Queen Anne', 'neighborhood=Wallingford', 'price', 'rooms']
['neighborhood=Fremont', 'neighborhood=Queen Anne', 'neighborhood=Wallingford', 'price', 'rooms']


# Q2: Feature Engineering - Text Features

- a. print B1
- b. import CountVectorizer from sklearn
- c. CountVectorize the B1, then print it
- d. print the feature name of Q2c.
- e. using pandas dataframe to print the result of Q2c.(with feature name)
- f. import TfidfVectorizer from sklearn
- g. TfidfVectorize the B1, then print it by pandas dataframe(with feature name)

## Q2a print B1

In [46]:
## here for print code
print(B1)

['Human machine interface for lab computer', 'A survey of user opinion of computer system', 'User interface management system', 'Graph minors A survey']


# Q2b import CountVectorizer from sklearn

In [47]:
## here for import code\
from sklearn.feature_extraction.text import CountVectorizer

## Q2c CountVectorize the B1, then print it

In [49]:
## here for print code
vec3 = CountVectorizer()
print(vec3.fit_transform(B1))

  (0, 3)	1
  (0, 6)	1
  (0, 4)	1
  (0, 1)	1
  (0, 5)	1
  (0, 0)	1
  (1, 0)	1
  (1, 11)	1
  (1, 9)	2
  (1, 13)	1
  (1, 10)	1
  (1, 12)	1
  (2, 4)	1
  (2, 13)	1
  (2, 12)	1
  (2, 7)	1
  (3, 11)	1
  (3, 2)	1
  (3, 8)	1


## Q2d print the feature name of Q2c.

In [50]:
## here for print code
print(vec3.get_feature_names())

['computer', 'for', 'graph', 'human', 'interface', 'lab', 'machine', 'management', 'minors', 'of', 'opinion', 'survey', 'system', 'user']


# Q2e using pandas dataframe to print the result of Q2c.(with feature name)

In [51]:
## here for print code
pd.DataFrame(vec3.fit_transform(B1).toarray(), columns=vec3.get_feature_names_out())

computer  for  graph  human  interface  lab  machine  management  minors  \
0         1    1      0      1          1    1        1           0       0   
1         1    0      0      0          0    0        0           0       0   
2         0    0      0      0          1    0        0           1       0   
3         0    0      1      0          0    0        0           0       1   

   of  opinion  survey  system  user  
0   0        0       0       0     0  
1   2        1       1       1     1  
2   0        0       0       1     1  
3   0        0       1       0     0

## Q2f import TfidfVectorizer from sklearn

In [53]:
## here for import code
from sklearn.feature_extraction.text import TfidfVectorizer 

## Q2g TfidfVectorize the B1, then print it by pandas dataframe(with feature name)

In [54]:
## here for print code
vec4 = TfidfVectorizer()
pd.DataFrame(vec4.fit_transform(B1).toarray(), columns=vec4.get_feature_names_out())

computer       for     graph     human  interface       lab   machine  \
0  0.344315  0.436719  0.000000  0.436719   0.344315  0.436719  0.436719   
1  0.288149  0.000000  0.000000  0.000000   0.000000  0.000000  0.000000   
2  0.000000  0.000000  0.000000  0.000000   0.465809  0.000000  0.000000   
3  0.000000  0.000000  0.617614  0.000000   0.000000  0.000000  0.000000   

   management    minors        of   opinion    survey    system      user  
0    0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
1    0.000000  0.000000  0.730961  0.365481  0.288149  0.288149  0.288149  
2    0.590819  0.000000  0.000000  0.000000  0.000000  0.465809  0.465809  
3    0.000000  0.617614  0.000000  0.000000  0.486934  0.000000  0.000000

# Q3 Imputation of Missing Data

- a. print C1
- b. import Imputer from sklearn
- c. using strategy='mean' to imputate the C1, then print it
- d. using strategy='most_frequent' to imputate the C1, then print it

## Q3a print C1

In [55]:
## here for print code
print(C1)

[[nan  0.  3.]
 [ 3.  7.  9.]
 [ 3.  5.  2.]
 [ 4. nan  6.]
 [ 8.  8.  1.]]


## Q3b import SimpleImputer from sklearn

In [57]:
## here for import code
from sklearn.impute import SimpleImputer

## Q3c using strategy='mean' to imputate the C1, then print it

In [58]:
## here for print code
imp = SimpleImputer(missing_values=nan, strategy='mean')
print(imp.fit_transform(C1))

[[4.5 0.  3. ]
 [3.  7.  9. ]
 [3.  5.  2. ]
 [4.  5.  6. ]
 [8.  8.  1. ]]


## Q3d using strategy='most_frequent' to imputate the C1, then print it

In [59]:
## here for print code
imp = SimpleImputer(missing_values=nan, strategy='most_frequent')
print(imp.fit_transform(C1))

[[3. 0. 3.]
 [3. 7. 9.]
 [3. 5. 2.]
 [4. 0. 6.]
 [8. 8. 1.]]
