# MIS132 程式設計實習 - Lecture09

## Outline this week

- (二維)陣列運算介紹
- NumPy
  - NumPy 介紹
  - 陣列基礎
  - 建立陣列
  - 統計數值
- Lab 練習

## (二維)陣列運算介紹

基本 Python 中，一維陣列是基本且常用的資料結構，暫存結果、取代迴圈...等都是很重要的用法。

在**科學運算、資料分析**中則略有不同，二維陣列（或更高維度的陣列）是更常用到的資料型態。

科學計算通常指的是包含線性代數、矩陣運算、矩陣運算、數值分析、微積分...等功能。

以 Python 舉例，NumPy、Pandas、Matplotlib 這三個資料科學最常用的套件，都是以（二維）陣列為基底的系統，進一步說，他們都是以 NumPy 為主的，因此今天的主角就是 NumPy。

## Numpy
### Numpy 介紹

現在的科學運算有**絕大多數**都是以 NumPy 寫成的，Numpy 在 2020 年更是登上的最頂級的 Nature 期刊，介紹了這個強大無比的套件

![](https://i.imgur.com/XrNWbqS.png)

總結一下，Numpy 有以下這幾個優點：
1. 大量以**多維陣列為主的數學運算**函式
2. 執行速度超快（以 C 寫成）、擁有極佳的優化
3. 可以以 Numpy Array 取代 Python List
4. 被廣泛應用在機器學習、物理、化學、航空...等領域

總而言之，如果你要成為 Python 資料工程師，NumPy 是你一定要會的 Package 之一

### NumPy 陣列基礎

讓我們從基礎開始，首先我們要知道陣列的名詞，列（row）和欄（column）

![Image of Yaktocat](https://static.coderbridge.com/img/techbridge/images/kdchang/arrays.png)

接著我們可以開始 NumPying 了

In [3]:
import numpy as np
print(np.__version__)

1.22.3


Python 的陣列是 `list()` 或 `[]`，NumPy 陣列則是 `numpy.array`

使用 `numpy.array` 可以把 Python List 轉成 NumPy
```python
arr = np.array([1, 2, 3, 4, 5])
```

NumPy 有一個重點：**所有元素都要是同一型態，e.g. 整數、浮點數**，這點和 C 一模一樣，因為這樣才能在記憶體中更好的儲存大型陣列、在運算時也不用去判斷每個元素是什麼型態

In [2]:
a = np.array([1, 2, 3, 4, 5])
print('a ->', a)
print('a type', a.dtype)

b = np.array([1.1, 2.2, 3.3, 4.4])
print('b ->', b)
print('b type', b.dtype)

a -> [1 2 3 4 5]
a type int64
b -> [1.1 2.2 3.3 4.4]
b type float64


In [3]:
a

array([1, 2, 3, 4, 5])

當我們有了 NumPy 的陣列後，我們可以先看看陣列的一些重要屬性，例如他的形狀和元素大小

這在運算中通常很好用

| Function | Description |
| :---: | --- |
| arr.ndim | array 的維度 |
| **arr.shape** | array 每個維度的 size，會回傳 Tuple |
| arr.size | array 總元素數量，等於 shape 的相乘 |
| **arr.dtype** | array 內變數的型態，e.g. int64, float64 |
| arr.itemsize | 陣列內每個元素的大小（Bytes） |
| arr.nbytes | 陣列內所有元素的大小（Bytes），等於 size * itemsize |

In [4]:
aa = np.array([[1, 3, 5, 7], [2, 4, 6, 8]])
print('aa', aa)
print('-----------')
print('ndim\t:', aa.ndim)
print('shape\t:', aa.shape)
print('size\t:', aa.size)
print('dtype\t:', aa.dtype)
print('itemsize:', aa.itemsize)
print('nbytes\t:', aa.nbytes)

aa [[1 3 5 7]
 [2 4 6 8]]
-----------
ndim	: 2
shape	: (2, 4)
size	: 8
dtype	: int32
itemsize: 4
nbytes	: 32


### 建立陣列

除了從 Python List 把所有元素打出來，我們可以用一些 Function 來建立陣列

#### np.arange

```python
np.arange( 起始值, 結束值, 步幅, dtype=資料型態 )
```

arange 可以像是 Python 的 range 一樣，快速且自動化建立好陣列、初始化所有內容

In [5]:
# # trick to display all outputs instread the last one
# from IPython.core.interactiveshell import InteractiveShell
# # InteractiveShell.ast_node_interactivity = 'last' # original setting
# InteractiveShell.ast_node_interactivity = 'all'

In [6]:
c1 = np.arange(10)
# like -> list(range(10))
c1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
c2 = np.arange(3, 9)
c2

array([3, 4, 5, 6, 7, 8])

In [8]:
c3 = np.arange(5, 15, 1.5, dtype=np.float)
c3

/var/folders/yb/vl7yj3hd0mvd1j5t18vzth880000gn/T/ipykernel_93016/112194571.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  c3 = np.arange(5, 15, 1.5, dtype=np.float)


array([ 5. ,  6.5,  8. ,  9.5, 11. , 12.5, 14. ])

---

#### np.zeros & np.ones

```python
np.zeros( ( 陣列每個維度的大小 ) )
np.ones( ( 陣列每個維度的大小 ) )
```

zeros 能建立全部為零的陣列，裡面的參數代表每個維度的 size，類似 shape 會回傳的結果
ones 則是全部為一的陣列

In [9]:
d1 = np.zeros(3)
d1

array([0., 0., 0.])

In [10]:
d1.dtype

dtype('float64')

In [35]:
# 會出錯
# d2 = np.zeros(2, 5) # 不能傳入 2 個參數，要傳入「1 個 tuple 內含 2 個數字」才可以

In [11]:
d2 = np.zeros((2, 5))
d2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
d3 = np.zeros((3, 2, 3))
d3

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [13]:
d4 = np.ones((2, 5))
d4

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
d5 = np.ones((5, 2))
d5

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
d6 = np.ones((1, 1, 1))
# or 考慮用 .squeeze 來處理
d6

array([[[1.]]])

---
#### np.ranndom.rand

```python
np.ranndom.rand( 陣列大小 )
```

用隨機數值（float）初始化給定 size 的一維陣列，range 為 0~1

In [16]:
e1 = np.random.rand(3)
e1

array([0.11813785, 0.55069187, 0.37049376])

In [17]:
e2 = np.random.rand(10)
e2

array([0.01847021, 0.00758915, 0.05868624, 0.07258856, 0.02569261,
       0.19872129, 0.23377923, 0.23829357, 0.85163463, 0.43465695])

---
#### np.linspace

```python
np.linspace( 起始值, 結束值, 元素個數 )
```

linspace 在繪圖時很常用到，會在給定的範圍內平均地產出你指定數量的數字

In [18]:
f1 = np.linspace(3, 5, 9)
f1

array([3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [19]:
f1.shape

(9,)

In [20]:
f2 = np.linspace(1, 11, 19)
f2

array([ 1.        ,  1.55555556,  2.11111111,  2.66666667,  3.22222222,
        3.77777778,  4.33333333,  4.88888889,  5.44444444,  6.        ,
        6.55555556,  7.11111111,  7.66666667,  8.22222222,  8.77777778,
        9.33333333,  9.88888889, 10.44444444, 11.        ])

In [21]:
f3 = np.linspace(5, 10, 11)
f3

array([ 5. ,  5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

### 統計函數

np 針對最常用的統計函數表現非常優異，e.g. mean, max, std...等

<font color='red'>重要！你有兩種用法可以使用</color>
1. `np.mean(array_name)`
2. `array_name.mean()`

下面介紹幾種方法，並和原始 Python List 比較速度

#### np.mean()
回傳 mean 平均值

In [5]:
g1 = np.arange(1, 16, 1.5)
g1

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. , 11.5, 13. , 14.5])

In [6]:
np.mean(g1)

7.75

In [7]:
g1.mean()
# 後面範例以這種方式為主

7.75

---
#### np.max() & np.min()
回傳 min 和 max 最大最小值

In [24]:
g2 = np.random.rand(10)
g2

array([0.59219243, 0.35223626, 0.22317217, 0.4906097 , 0.79264391,
       0.73409181, 0.87179432, 0.10078101, 0.37691464, 0.59564422])

In [25]:
g2.min()

0.10078101048741728

In [26]:
g2.max()

0.8717943165282939

---
#### 針對二維陣列的操作

上面提到的幾種 function 可以用 axis 來指定我們運算的範圍
```python
np.max(g3, axis=int)
g3.max(axis=int)
```

In [11]:
g3 = np.random.rand(9).reshape(3, 3)
print(g3)
print('---')
print(g3.max())           # 所有元素的最大值
print(g3.max(axis=0))     # 每個 column 的最大值
print(g3.max(axis=1))     # 每個 row 的最大值
print('---')
print(np.max(g3))         # 所有元素的最大值
print(np.max(g3, axis=0)) # 每個 column 的最大值
print(np.max(g3, axis=1)) # 每個 row 的最大值

[[0.48256368 0.55484628 0.60912261]
 [0.92819357 0.7862191  0.00407556]
 [0.51597255 0.14696987 0.32821533]]
---
0.928193565888449
[0.92819357 0.7862191  0.60912261]
[0.60912261 0.92819357 0.51597255]
---
0.928193565888449
[0.92819357 0.7862191  0.60912261]
[0.60912261 0.92819357 0.51597255]


### Lab練習

請開啟一份新的 .ipynb 筆記檔案, 檔名為「L09.ipynb」，寫完上傳至網大.

- 請利用 numpy 建立以下 array

1. 建立一個長度為 15 的隨機向量，每個數值介在 0~2 hint: random.rand
2. 建立一个 6 x 6 的矩陣，其中每個的數值介在 0~5 hint: reshape
3. 建立一個 3x3x3 的隨機矩陣，分別計算所有的、按照 axis=0、按照 axis=2 的 mean
4. 了解 reshape、dot 或任意 numpy function 的用法，並舉出兩個實際操作的例子