1. 建立一個長度為 15 的隨機向量，每個數值介在 0~2

In [78]:
import numpy as np

a = np.random.uniform(0, 2, 15)

print(a)

[1.55377893 0.58983938 0.30997356 1.51838392 0.35260261 1.83967115
 1.40666261 1.15524832 0.2595012  1.74991355 0.36216069 0.89568176
 0.92865797 0.31407946 0.86489572]


2. 建立一个 6 x 6 的矩陣，其中每個的數值介在 0~5 hint: reshape

In [108]:
import numpy as np

a = np.random.uniform(0, 5, 36).reshape(6, 6)

print(a)

[[2.98215614 1.62719069 0.74956625 4.42566687 1.77198747 4.25955128]
 [4.26107474 0.70030838 1.35594169 1.03517299 3.96815712 2.02716734]
 [3.58159644 3.26853512 3.27937965 2.71128471 3.07021453 2.8769668 ]
 [0.79610266 1.54927387 3.65675496 2.86629223 1.09499769 2.70695565]
 [4.70194844 0.50784545 2.78817877 3.73713728 1.84287915 4.89076362]
 [4.91867909 3.76114029 2.55891543 2.68910023 3.27586269 4.69442071]]


3. 建立一個 3x3x3 的隨機矩陣，分別計算所有的、按照 axis=0、按照 axis=2 的 mean

In [109]:
import numpy as np

a = np.random.uniform(size=27).reshape(3, 3, 3)

print(a)
print('---')
print('All elements mean = ', a.mean())
print('Axis=0 elements mean = ', a.mean(axis=0))
print('Axis=2 elements mean = ', a.mean(axis=2))



[[[0.41563724 0.54992241 0.79205898]
  [0.69329207 0.40802865 0.27435855]
  [0.83760489 0.04582638 0.99653967]]

 [[0.25009932 0.62660127 0.82074859]
  [0.42128361 0.89831866 0.08353867]
  [0.45686723 0.07380801 0.15153711]]

 [[0.72675354 0.86227731 0.23983357]
  [0.34553592 0.93389241 0.57957374]
  [0.7959616  0.06755783 0.33990493]]]
---
All elements mean =  0.5069393403702854
Axis=0 elements mean =  [[0.46416337 0.67960033 0.61754705]
 [0.48670386 0.74674658 0.31249032]
 [0.69681124 0.06239741 0.4959939 ]]
Axis=2 elements mean =  [[0.58587288 0.45855975 0.62665698]
 [0.56581639 0.46771365 0.22740412]
 [0.60962148 0.61966736 0.40114146]]


4. 了解 reshape、dot 或任意 numpy function 的用法，並舉出兩個實際操作的例子

* `random.uniform(n, m, c)`
    * 產生數為浮點數
    * n~m為範圍
    * c為產生資料數

* `reshape(n1, n2, ...)`
    * 將目前資料轉換成 n1 * n2 * ... 的陣列
    * 其中一個數據可以為`-1 `代表需要計算
    * 須確保待轉換陣列數組數是可以轉換成後方的，否則會報錯

* `dot(a, b)`
    * 主要實現矩陣內積運算
    * 在a為mxn條件下，b須為nxp或者n矩陣


In [112]:
import numpy as np

a = np.array([[1, 2, 3], 
              [4, 5, 6]])
b = np.array([[1, 2],
              [3, 4],
              [5, 6]])

print('a = ', a)
print('b = ', b)

print('a dot b = ', np.dot(a, b))

a =  [[1 2 3]
 [4 5 6]]
b =  [[1 2]
 [3 4]
 [5 6]]
a dot b =  [[22 28]
 [49 64]]


In [117]:
import numpy as np

a = np.random.uniform(-1, 1, 12).reshape(3, -1)
b = np.random.uniform(-1, 1, 12).reshape(-1, 3)

print('a = ', a)
print('b = ', b)

print('a dot b = ', np.dot(a, b))

a =  [[ 0.08754168 -0.88316145  0.51314014 -0.83289719]
 [ 0.69456098 -0.48094115  0.7473821   0.64764354]
 [ 0.72154996 -0.80881057 -0.31931405  0.64107567]]
b =  [[-0.51717296  0.7143758   0.78303123]
 [ 0.87970581 -0.35325852 -0.49663303]
 [ 0.48079837  0.46107269 -0.4392533 ]
 [ 0.96549288  0.22355627 -0.25553948]]
a dot b =  [[-1.37963581  0.42491748  0.49459463]
 [ 0.20234044  1.15545637  0.28892565]
 [-0.61925315  0.79726655  0.94311779]]
