# Numpy
## How to use


For installation use `python -m pip install numpy`
We common use np to stand for numpy

In [1]:
import numpy as np

Check version

In [2]:
np.version.version

'1.22.2'

Document

In [3]:
np?

Type:        module
String form: <module 'numpy' from 'c:\\Users\\eddie\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\eddie\appdata\local\programs\python\python310\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippe

---
## Example
### Create a simple array

In [4]:
np.array([1, 2, 3])

array([1, 2, 3])

Can set the data type by using `dtype`

In [5]:
a = np.array([1, 2, 3], dtype='float32')

Check the array dimention

In [6]:
a.shape

(3,)

Create a 2 * 2 array

In [7]:
b = np.array([[1, 2], [3, 4]])

In [8]:
b.shape

(2, 2)

In [9]:
b

array([[1, 2],
       [3, 4]])

---

### Custom array
Single demention array with fill values 0

In [10]:
# single demention array with fill values 0
# np.zeros(size, dtype)
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Multiple demention array with fill values 1

In [11]:
# multiple demention array with fill values 1
# np.ones(size, dtype)
np.ones((3,5), dtype=int) 

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

Full the array with custom values

In [12]:
# full the array with custom values
# np.full(array, value)
np.full((3, 4), 3.14) 

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

Create a arange array

In [13]:
# np.arange(start, end, step)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

Create an array with a linear squence

In [14]:
# create an array with a linear squence
# np.linspace(start, end, amount)
np.linspace(0, 2, 5)

array([0. , 0.5, 1. , 1.5, 2. ])

Create a 3 * 3 array of uniform distributed random number between 0 and 1

In [15]:
# create a 3 * 3 array of uniform distributed random number between 0 and 1
# np.random.random(size)
np.random.random((3, 3))

array([[0.29651422, 0.12158306, 0.99449098],
       [0.90808503, 0.28556388, 0.94143599],
       [0.65485967, 0.13597407, 0.72674309]])

Create a 3 * 3 array of natural destruction with mean and standard deviation 1

In [16]:
# create a 3 * 3 array of natural destruction with mean and standard deviation 1
# np.random.normal(start, end, size)
np.random.normal(0, 1, (3, 3))

array([[-0.53545591,  0.39302625, -0.00395988],
       [ 0.64289112, -1.08629631,  0.61208573],
       [-0.72183395, -0.11151797,  1.21128933]])

Create array of random integers between 0 and 100

In [17]:
# create array of random integers between 0 and 100
# np.random.randint(start, end, size)
np.random.randint(0, 10, (3, 3))

array([[2, 3, 3],
       [7, 6, 2],
       [2, 5, 2]])

Indentity array

In [18]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

---
## Basics of NumPy Arrays
* Attribute of arrays
* Indexing of arrays
* Slicing of Arrays
* Reshaping of arrays
* Concatenating and splitting of arrays
---

### Attribute of arrays
Set seed

In [19]:
np.random.seed(0)

Create variables

In [20]:
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3, 4, 5))

About shape

In [21]:
print(x1.shape)
print(x2.shape)
print(x3.shape)

(6,)
(3, 4)
(3, 4, 5)


About size

In [22]:
print(x1.size)
print(x2.size)
print(x3.size)

6
12
60


About data type

In [23]:
print(x1.dtype)
print(x2.dtype)
print(x3.dtype)

int32
int32
int32


About item size

In [24]:
print(x1.itemsize)
print(x2.itemsize)
print(x3.itemsize)

4
4
4


About nBytes

In [25]:
print(x1.nbytes)
print(x2.nbytes)
print(x3.nbytes)

24
48
240


About dimension

In [26]:
print(x1.ndim)
print(x2.ndim)
print(x3.ndim)

1
2
3


1. [x] Arrtibute of arrays
2. [ ] Indexing of arrays
3. [ ] Slicing of arrays
4. [ ] Reshaping of arrays
5. [ ] Concatenate and spliting arrays
---

### Indexing of arrays

Index start with 0 or back from -1

In [27]:
x1

array([5, 0, 3, 3, 7, 9])

In [28]:
x1[0]

5

In [29]:
x1[5]

9

In [30]:
x1[-1]

9

In [31]:
x1[-6]

5

Now in 2 dimension

In [32]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [33]:
x2[0][0]

3

In [34]:
x2[0, 0]

3

In [35]:
x2[0, 2]

2

In [36]:
x2[2, -1]

7

Change value of element

In [37]:
x2[0, 0] = 12

In [38]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

What if we try insert a float

In [39]:
x1.dtype

dtype('int32')

In [40]:
x1

array([5, 0, 3, 3, 7, 9])

In [41]:
x1[0] = 3.1415926

It will convert to integer

In [42]:
x1

array([3, 0, 3, 3, 7, 9])

1. [x] Arrtibute of arrays
2. [x] Indexing of arrays
3. [ ] Slicing of arrays
4. [ ] Reshaping of arrays
5. [ ] Concatenate and spliting arrays
---

### Slicing of arrays

In [43]:
x = np.arange(10)

In [44]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Slicing by using `var[start:stop:step]`

First 5 elements

In [45]:
x[:5]

array([0, 1, 2, 3, 4])

After 5 elements

In [46]:
x[5:]

array([5, 6, 7, 8, 9])

Access middle subarray

In [47]:
x[4:7]

array([4, 5, 6])

Access every other element after 1 step by 3

In [48]:
x[1::3]

array([1, 4, 7])

Access every from 1 to 8 step by 2

In [49]:
x[1:8:2]

array([1, 3, 5, 7])

Reverse the array by using `[::-1]`

In [50]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Reverse and choose starting point

In [51]:
x[5::-2]

array([5, 3, 1])

How about 2 dimention array

In [52]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [53]:
x2[1:3, :]

array([[7, 6, 8, 8],
       [1, 6, 7, 7]])

In [54]:
x2[:, :0:-1]

array([[4, 2, 5],
       [8, 8, 6],
       [7, 7, 6]])

In [55]:
x2[::, ::-1]

array([[ 4,  2,  5, 12],
       [ 8,  8,  6,  7],
       [ 7,  7,  6,  1]])

In [56]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

1. [x] Arrtibute of arrays
2. [x] Indexing of arrays
3. [x] Slicing of arrays
4. [ ] Reshaping of arrays
5. [ ] Concatenate and spliting arrays
---

### Reshaping of arrays

Using `reshape(size)`


**The size need match array element amounts**

In [57]:
grid = np.arange(1,10).reshape(3, 3)

In [58]:
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
grid1 = np.arange(1,4).reshape(1, 1, 3)

In [60]:
grid1

array([[[1, 2, 3]]])

Dimention of array

In [61]:
grid1.ndim

3

In [62]:
grid2 = np.arange(1, 10).reshape(9, 1)

In [63]:
grid2

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

1. [x] Arrtibute of arrays
2. [x] Indexing of arrays
3. [x] Slicing of arrays
4. [x] Reshaping of arrays
5. [ ] Concatenate and spliting arrays
---

### Concatenate and spliting arrays
#### Concatenate

In [64]:
x = np.arange(1, 4)
y = np.arange(9, 6, -1)

In [65]:
x

array([1, 2, 3])

In [66]:
y

array([9, 8, 7])

In [67]:
np.concatenate([x, y])

array([1, 2, 3, 9, 8, 7])

In [68]:
np.concatenate([x, y]).dtype

dtype('int32')

In [69]:
z = np.array([3.14, 3.14])

In [70]:
np.concatenate([x, y, z])

array([1.  , 2.  , 3.  , 9.  , 8.  , 7.  , 3.14, 3.14])

In [71]:
np.concatenate([x, y, z]).dtype

dtype('float64')

In [72]:
grid1 = np.arange(1, 7).reshape(2, 3)
grid2 = np.arange(8, 14).reshape(2, 3)

In [73]:
np.concatenate([grid1, grid2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [11, 12, 13]])

Vertical Stack

In [74]:
np.vstack([x, grid1])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [75]:
grid3 = np.array([[99], [99]])

Horizontal Stack

In [76]:
np.hstack([grid3, grid1])

array([[99,  1,  2,  3],
       [99,  4,  5,  6]])

#### Split

In [77]:
x = np.array([1, 2, 3, 99, 99, 3, 2, 1])

In [78]:
# np.split(array, [where to cut])
grid1, grid2, grid3 = np.split(x, [3, 5])

In [79]:
grid1

array([1, 2, 3])

In [80]:
grid2

array([99, 99])

In [81]:
grid3

array([3, 2, 1])

In [82]:
grid = np.arange(16).reshape(4, 4)

In [83]:
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

Vertical split

In [84]:
# np.split(array, where to cut)
upper, lower = np.vsplit(grid, [2])

In [85]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [86]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

Horizontal split

In [87]:
left, right = np.hsplit(grid, [2])

In [88]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [89]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

1. [x] Arrtibute of arrays
2. [x] Indexing of arrays
3. [x] Slicing of arrays
4. [x] Reshaping of arrays
5. [x] Concatenate and spliting arrays
---