# Numpy
## How to use


For installation use `python -m pip install numpy`
We common use np to stand for numpy

In [38]:
import numpy as np

Check version

In [39]:
np.version.version

'1.22.2'

Document

In [40]:
np?

Type:        module
String form: <module 'numpy' from 'c:\\Users\\eddie\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\eddie\appdata\local\programs\python\python310\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippe

---
## Example
### Create a simple array

In [41]:
np.array([1, 2, 3])

array([1, 2, 3])

Can set the data type by using `dtype`

In [42]:
a = np.array([1, 2, 3], dtype='float32')

Check the array dimention

In [43]:
a.shape

(3,)

Create a 2 * 2 array

In [44]:
b = np.array([[1, 2], [3, 4]])

In [45]:
b.shape

(2, 2)

In [46]:
b

array([[1, 2],
       [3, 4]])

---

### Custom array
Single demention array with fill values 0

In [47]:
# single demention array with fill values 0
# np.zeros(size, dtype)
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Multiple demention array with fill values 1

In [48]:
# multiple demention array with fill values 1
# np.ones(size, dtype)
np.ones((3,5), dtype=int) 

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

Full the array with custom values

In [49]:
# full the array with custom values
# np.full(array, value)
np.full((3, 4), 3.14) 

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

Create a arange array

In [50]:
# np.arange(start, end, step)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

Create an array with a linear squence

In [51]:
# create an array with a linear squence
# np.linspace(start, end, amount)
np.linspace(0, 2, 5)

array([0. , 0.5, 1. , 1.5, 2. ])

Create a 3 * 3 array of uniform distributed random number between 0 and 1

In [52]:
# create a 3 * 3 array of uniform distributed random number between 0 and 1
# np.random.random(size)
np.random.random((3, 3))

array([[0.93476733, 0.59715138, 0.53110842],
       [0.57097665, 0.31415448, 0.20754131],
       [0.32487316, 0.20285857, 0.29372469]])

Create a 3 * 3 array of natural destruction with mean and standard deviation 1

In [53]:
# create a 3 * 3 array of natural destruction with mean and standard deviation 1
# np.random.normal(start, end, size)
np.random.normal(0, 1, (3, 3))

array([[-0.44202418, -0.34718691, -0.86103767],
       [-1.01094212, -0.44377762, -0.167425  ],
       [ 1.93104356, -0.45336675, -0.81724147]])

Create array of random integers between 0 and 100

In [54]:
# create array of random integers between 0 and 100
# np.random.randint(start, end, size)
np.random.randint(0, 10, (3, 3))

array([[3, 1, 5],
       [7, 9, 1],
       [2, 2, 6]])

---
## Basics of NumPy Arrays
* Attribute of arrays
* Indexing of arrays
* Slicing of Arrays
* Reshaping of arrays
* Concatenating and splitting of arrays
---

### Attribute of arrays
Set seed

In [55]:
np.random.seed(0)

Create variables

In [57]:
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3, 4, 5))

About shape

In [58]:
print(x1.shape)
print(x2.shape)
print(x3.shape)

(6,)
(3, 4)
(3, 4, 5)


About size

In [59]:
print(x1.size)
print(x2.size)
print(x3.size)

6
12
60


About data type

In [60]:
print(x1.dtype)
print(x2.dtype)
print(x3.dtype)

int32
int32
int32


About item size

In [61]:
print(x1.itemsize)
print(x2.itemsize)
print(x3.itemsize)

4
4
4


About nBytes

In [62]:
print(x1.nbytes)
print(x2.nbytes)
print(x3.nbytes)

24
48
240


1. [x] Arrtibute of arrays
2. [ ] Indexing of arrays
3. [ ] Slicing of arrays
4. [ ] Reshaping of arrays
5. [ ] Concatenate and spliting arrays
---

### Indexing of arrays

Index start with 0 or back from -1

In [63]:
x1

array([5, 0, 3, 3, 7, 9])

In [64]:
x1[0]

5

In [65]:
x1[5]

9

In [66]:
x1[-1]

9

In [69]:
x1[-6]

5

Now in 2 dimension

In [70]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [71]:
x2[0][0]

3

In [75]:
x2[0, 0]

3

In [77]:
x2[0, 2]

2

In [76]:
x2[2, -1]

7

Change value of element

In [78]:
x2[0, 0] = 12

In [79]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

What if we try insert a float

In [80]:
x1.dtype

dtype('int32')

In [81]:
x1

array([5, 0, 3, 3, 7, 9])

In [82]:
x1[0] = 3.1415926

It will convert to integer

In [83]:
x1

array([3, 0, 3, 3, 7, 9])

1. [x] Arrtibute of arrays
2. [x] Indexing of arrays
3. [ ] Slicing of arrays
4. [ ] Reshaping of arrays
5. [ ] Concatenate and spliting arrays
---

### Slicing of arrays

In [85]:
x = np.arange(10)

In [86]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Slicing by using `var[start:stop:step]`

First 5 elements

In [87]:
x[:5]

array([0, 1, 2, 3, 4])

After 5 elements

In [88]:
x[5:]

array([5, 6, 7, 8, 9])

Access middle subarray

In [89]:
x[4:7]

array([4, 5, 6])

Access every other element after 1 step by 3

In [91]:
x[1::3]

array([1, 4, 7])

Access every from 1 to 8 step by 2

In [92]:
x[1:8:2]

array([1, 3, 5, 7])

Reverse the array by using `[::-1]`

In [93]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Reverse and choose starting point

In [94]:
x[5::-2]

array([5, 3, 1])

How about 2 dimention array

In [113]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [112]:
x2[1:3, :]

array([[7, 6, 8, 8],
       [1, 6, 7, 7]])

In [121]:
x2[:, :0:-1]

array([[4, 2, 5],
       [8, 8, 6],
       [7, 7, 6]])

In [122]:
x2[::, ::-1]

array([[ 4,  2,  5, 12],
       [ 8,  8,  6,  7],
       [ 7,  7,  6,  1]])

In [120]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

1. [x] Arrtibute of arrays
2. [x] Indexing of arrays
3. [x] Slicing of arrays
4. [ ] Reshaping of arrays
5. [ ] Concatenate and spliting arrays
---

### Reshaping of arrays

Using `reshape(size)`


**The size need match array element amounts**

In [127]:
grid = np.arange(1,10).reshape(3, 3)

In [128]:
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [136]:
grid1 = np.arange(1,4).reshape(1, 1, 3)

In [137]:
grid1

array([[[1, 2, 3]]])

Dimention of array

In [138]:
grid1.ndim

3

In [151]:
grid2 = np.arange(1, 10).reshape(9, 1)

In [152]:
grid2

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

1. [x] Arrtibute of arrays
2. [x] Indexing of arrays
3. [x] Slicing of arrays
4. [x] Reshaping of arrays
5. [ ] Concatenate and spliting arrays
---

### Concatenate and spliting arrays
#### Concatenate

In [159]:
x = np.arange(1, 4)
y = np.arange(9, 6, -1)

In [163]:
x

array([1, 2, 3])

In [164]:
y

array([9, 8, 7])

In [166]:
np.concatenate([x, y])

array([1, 2, 3, 9, 8, 7])

In [170]:
np.concatenate([x, y]).dtype

dtype('int32')

In [185]:
z = np.array([3.14, 3.14])

In [186]:
np.concatenate([x, y, z])

array([1.  , 2.  , 3.  , 9.  , 8.  , 7.  , 3.14, 3.14])

In [187]:
np.concatenate([x, y, z]).dtype

dtype('float64')

In [181]:
grid1 = np.arange(1, 7).reshape(2, 3)
grid2 = np.arange(8, 14).reshape(2, 3)

In [182]:
np.concatenate([grid1, grid2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [11, 12, 13]])

Vertical Stack

In [184]:
np.vstack([x, grid1])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [192]:
grid3 = np.array([[99], [99]])

Horizontal Stack

In [197]:
np.hstack([grid3, grid1])

array([[99,  1,  2,  3],
       [99,  4,  5,  6]])

#### Split

In [199]:
x = np.array([1, 2, 3, 99, 99, 3, 2, 1])

In [216]:
# np.split(array, [where to cut])
grid1, grid2, grid3 = np.split(x, [3, 5])

In [213]:
grid1

array([1, 2, 3])

In [214]:
grid2

array([99, 99])

In [215]:
grid3

array([3, 2, 1])

In [201]:
grid = np.arange(16).reshape(4, 4)

In [202]:
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

Vertical split

In [227]:
# np.split(array, where to cut)
upper, lower = np.vsplit(grid, [2])

In [228]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [229]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

Horizontal split

In [224]:
left, right = np.hsplit(grid, [2])

In [225]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [226]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

1. [x] Arrtibute of arrays
2. [x] Indexing of arrays
3. [x] Slicing of arrays
4. [x] Reshaping of arrays
5. [ ] Concatenate and spliting arrays
---