# NumPy Arrays

In [1]:
import numpy as np

## **Q1- Create one dimensional array using python list**
- Data type needs to be float64 
- Print dtype, shape, size, dimension, and memory consumption of each element and total array

In [9]:
#create
arr0 = np.array([1, 2, 3, 4, 5], dtype=float)

In [10]:
# print
print(f'Data type = {arr0.dtype}')
print(f'Shape = {arr0.shape}')
print(f'Size = {arr0.size}')
print(f'Dimension = {arr0.ndim}')
print(f'Each element memory size = {arr0.itemsize}')
print(f'Total array memory size = {arr0.nbytes}')

Data type = float64
Shape = (5,)
Size = 5
Dimension = 1
Each element memory size = 8
Total array memory size = 40


## **Q2- Create two dimensional array using python list**
- Print dtype, shape, size, dimension, and memory consumption of each element and total array

In [13]:
#create
arr1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]], dtype='int64')

In [14]:
#print
print(f'Data type = {arr1.dtype}')
print(f'Shape = {arr1.shape}')
print(f'Size = {arr1.size}')
print(f'Dimension = {arr1.ndim}')
print(f'Each element memory size = {arr1.itemsize}')
print(f'Total array memory size = {arr1.nbytes}')

Data type = int64
Shape = (2, 4)
Size = 8
Dimension = 2
Each element memory size = 8
Total array memory size = 64


## **Q3- Create a length of 10 integer array filled with zeros**

In [3]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## **Q4- Create a 4X5 floating point array filled with 1s**

In [4]:
np.ones((4, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## **Q5- Create a 3x3 identity matrix**
- Data type: int

In [9]:
np.identity(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

## **Q6- Create a one dimensional array of length 10**
- Use numpy function arange to create the array
- Assign new value (12) at the index of 5,6,7

In [17]:
#create
arr2 = np.arange(10, dtype=int)

In [16]:
#asign
arr2[5:8] = 12
arr2

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

## **Q7- Create a 3x3 array**
- a. Use numpy function arange and reshape() to create the array
- b. Select the first two rows of array
- c. Select the second row but only the first two columns 
- d. Select the third column but only the first two rows
- e. Select the first column only
- f. Assign the new value 15 to the last element of third row and third column and print the array

In [20]:
# a.
# code
arr3 = np.arange(1, 10).reshape(3,3)

In [21]:
#print
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
# b.
arr3[:2,]

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
# c.
arr3[1,:2]

array([4, 5])

In [32]:
# d.
arr3[:2, 2]

array([[1],
       [4],
       [7]])

In [33]:
# e.
arr3[:,:1]

array([[1],
       [4],
       [7]])

In [34]:
# f.
arr3[2, 2] = 15

In [35]:
arr3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 15]])

## **Q8- Create two arrays of 3x1 and 3x3 shape**
- Join both the arrays horizontally and store the result in variable concat
- Split the concat array into 2x3 and 1x3 shape

In [38]:
#code
arr4 = np.arange(97, 100).reshape(3, 1)

In [39]:
#print
arr4

array([[97],
       [98],
       [99]])

In [40]:
#code
arr5 = np.arange(1, 10).reshape(3, 3)

In [41]:
#print
arr5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
#code
arr6 = np.hstack([arr4, arr5])

In [49]:
#print
arr6

array([[97,  1,  2,  3],
       [98,  4,  5,  6],
       [99,  7,  8,  9]])

In [50]:
np.vsplit(arr6, [2])

[array([[97,  1,  2,  3],
        [98,  4,  5,  6]]),
 array([[99,  7,  8,  9]])]

In [51]:
np.hsplit(arr6, [2])

[array([[97,  1],
        [98,  4],
        [99,  7]]),
 array([[2, 3],
        [5, 6],
        [8, 9]])]

In [52]:
np.hsplit(arr6, [3])

[array([[97,  1,  2],
        [98,  4,  5],
        [99,  7,  8]]),
 array([[3],
        [6],
        [9]])]